# Generated by Django 2.1.2 on 2018-12-07 18:15

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='file',
            field=models.FileField(null=True, upload_to=app.models.user_directory_path),
        ),
    ]
