# Generated by Django 2.1.2 on 2018-12-27 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181227_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='app.Project'),
        ),
    ]
