# Generated by Django 2.1.2 on 2019-01-02 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20181227_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
