# Generated by Django 2.1.2 on 2019-01-03 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190102_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='description',
        ),
    ]
