# Generated by Django 2.1.2 on 2019-01-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190131_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dir_path',
            field=models.FileField(default='data/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.CharField>', upload_to=''),
        ),
    ]
