# Generated by Django 2.1.2 on 2019-01-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_project_dir_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dir_path',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
