# Generated by Django 2.1.2 on 2019-01-31 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_sample_directory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='directory',
        ),
    ]
